---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafe-coffee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cafe-coffee
  template:
    metadata:
      labels:
        app: cafe-coffee
    spec:
      containers:
      - name: cafe-coffee
        image: azfaralam440/cafe-coffee:latest
        ports:
        - containerPort: 5173   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: cafe-coffee-service
spec:
  selector:
    app: cafe-coffee
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 5173
  type: LoadBalancer